# SPDX-FileCopyrightText: 2025 Jason LaGuidice
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- tags:
    - setup-all
    - setup-matrix-nether-voicebridge
    - setup-nether-voicebridge
    - install-all
    - install-matrix-nether-voicebridge
    - install-nether-voicebridge
  block:
    - when: matrix_nether_voicebridge_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_nether_voicebridge_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

- tags:
    - setup-all
    - setup-matrix-nether-voicebridge
    - setup-nether-voicebridge
  block:
    - when: not matrix_nether_voicebridge_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
